name: Generate Doxygen Docs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen via Chocolatey
        run: choco install doxygen.install -y

      - name: Cache Chocolatey Packages
        uses: actions/cache@v3
        with:
          path: C:/ProgramData/chocolatey/lib
          key: ${{ runner.os }}-choco-packages

      - name: Add Doxygen to PATH
        run: echo "C:\\Program Files\\doxygen\\bin" >> $env:GITHUB_PATH

      - name: Generate Doxygen documentation with pas2dox
        run: doxygen make\\doxygen.cfg
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
          force_orphan: true
